# Application Scaling
replicaCount: 2

# Container Image Config
image:
  repository: acrhospitalprod01.azurecr.io/hospital-app
  tag: "latest" # We will override this in CI/CD later
  pullPolicy: IfNotPresent

# Networking
service:
  type: ClusterIP
  port: 80
  targetPort: 3000

# Application Variables
appConfig:
  nodeEnv: "production"
  dbHost: "mongo-service"

# Secrets (In real life, use KeyVault. For this lab, we inject base64 here)
# echo -n "password" | base64
secrets:
  dbPassword: "cGFzc3dvcmQ="
  apiKey: "bXlfc3VwZXJfc2VjcmV0X2tleQ=="

# Resource Limits
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

# Persistence
persistence:
  enabled: true
  size: 1Gi
  storageClass: default