apiVersion: apps/v1
kind: Deployment
metadata:
  name: recruitment-app
spec:
  [cite_start]replicas: 2 # Scalability 
  selector:
    matchLabels:
      app: recruitment
  template:
    metadata:
      labels:
        app: recruitment
    spec:
      containers:
      - name: hospital-app
        # This matches the image we pushed in Step 2
        image: acrhospitalprod01.azurecr.io/hospital-app:latest 
        ports:
        - containerPort: 3000
        
        # Configuration Injection [cite: 59]
        envFrom:
        - configMapRef:
            name: recruitment-config
        - secretRef:
            name: recruitment-secret
            
        # Resource Limits (Crucial for Production) 
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
            
        # Health Checks (Observability)
        livenessProbe:
          httpGet:
            path: / # Adjust if you have a specific health route
            port: 3000
          initialDelaySeconds: 15
        readinessProbe:
          httpGet:
            path: /
            port: 3000
            
        # Mount the Volume for storage
        volumeMounts:
        - mountPath: "/app/uploads" # Folder inside container where resumes live
          name: storage-volume
          
      volumes:
      - name: storage-volume
        persistentVolumeClaim:
          claimName: recruitment-pvc