apiVersion: v1
kind: Service
metadata:
  name: recruitment-service
spec:
  type: ClusterIP
  selector:
    app: recruitment # Matches the Deployment label
  ports:
    - protocol: TCP
      port: 80       # The port other services will call
      targetPort: 3000 # The port your Node.js app is actually listening on